#!/bin/bash

# pomodoro - Start and run a pomodoro timer for use in tmux status line and elsewhere

# Copyright (C) 2015 Erik Stambaugh

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program (see the file LICENSE); if not, see
# http://www.gnu.org/licenses/, or write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301  USA

# Set some defaults
POMODORO_STATUS_FILE=/tmp/pom_$USER
POMODORO_BANG="❗"
POMODORO_SYMBOL="🍅"
POMODORO_NBSP=" "

test -e "$HOME/.pomodororc" && . "$HOME/.pomodororc"

case $1 in
    "status")
        if [ -e $POMODORO_STATUS_FILE ] || ([ ! -z "$POMODORO_SSH" ] && [ $(hostname) != "$POMODORO_NOSYNC_NAME" ]); then
            STATUS=$(cat $POMODORO_STATUS_FILE 2>/dev/null)

            if [ -z "$STATUS" ] && [ ! -z "$POMODORO_STATUS_URL" ] && [ $(hostname) != "$POMODORO_NOSYNC_NAME" ]; then
                STATUS=$(curl -s "$POMODORO_STATUS_URL" 2>/dev/null)
                if echo "$STATUS" | grep -q -E '[^0-9]'; then
                    STATUS=""
                fi
            fi

            if [ -z "$STATUS" ] && [ ! -z "$POMODORO_SSH" ] && [ $(hostname) != "$POMODORO_NOSYNC_NAME" ]; then
                ssh -q -o "ConnectTimeout 2" $POMODORO_SSH bin/pomodoro status 2>/dev/null
                exit 0
            elif [ -z "$STATUS" ]; then
                echo
            else
                DELTA=$(( 25 - $(($(( $(date +%s) - $STATUS )) / 60 )) ))
                if [ $DELTA -gt 0 ]; then
                    echo "${DELTA} ${POMODORO_SYMBOL} "
                else
                    echo "${POMODORO_BANG} ${POMODORO_NBSP} ${POMODORO_SYMBOL}"   # this line has a unicode nonbreaking space in it for format reasons
                fi
            fi
        else
            echo
        fi
        ;;

    "start")
        if [ ! -z "$POMODORO_SSH" ] && [ $(hostname) != "$POMODORO_NOSYNC_NAME" ]; then
            ssh -q -o "ConnectTimeout 2" $POMODORO_SSH bin/pomodoro start 2>&1 > /dev/null
        else
            date +%s > $POMODORO_STATUS_FILE
        fi
        tmux refresh-client -S
        ;;

    "clear")
        if [ ! -z "$POMODORO_SSH" ] && [ $(hostname) != "$POMODORO_NOSYNC_NAME" ]; then
            ssh -q -o "ConnectTimeout 2" $POMODORO_SSH bin/pomodoro clear 2>&1 > /dev/null
        fi
        rm -f $POMODORO_STATUS_FILE
        tmux refresh-client -S
        ;;

esac
